shader_path: "shaders/"
window:
  name: "City"
  width: 1200
  height: 800
random_seed: 508
builder:
  angle_spacing: 1.57
  min_length: 4
  max_length: 10
  road_width: 1
  max_iteration: 100
  road_color: [ 0.4, 0.4, 0.4, 1.0 ]
