shader_path: "shaders/"
window:
  name: "City"
  width: 1200
  height: 800
random_seed: 509
builder:
  angle_std: 0.2
  angle_spacing: 1.57
  min_length: 20
  max_length: 100
  road_width: 10
  min_distance: 10
  snap_distance: 5
  node_snap_distance: 5
  edge_snap_angle: 0.7
  max_iteration: 1000
  road_color: [ 0.4, 0.4, 0.4, 1.0 ]
